### ISSUE TITLE
The color when use the option ⟨opacity⟩

### ISSUE THREAD

**Issue by SSeanHsu** [hackl/tkz-network#1]
The color is not satisfactory when use the option ⟨opacity⟩. I notice that when I use `\Vertex[label = x_1, Math, color = blue, opacity = 0.2]{x_1}`, for instance, blue turns into purple. Just as the illustration below.

![image](https://user-images.githubusercontent.com/20944641/30095385-c9f574dc-9304-11e7-92b9-75482ce432b5.png)

**Comment by hackl** [comment]
This is due to the white background used. The new color is a result of mixing blue with a white color. (The same results are obtained if you use Inkscape or another drawing program). In order to get different blue colors, I recommend using the RGB option, since the default TikZ colors do not always give the desired results.

**Comment by SSeanHsu** [comment]
@hackl OK, thanks a lot.
